# Project Commands
# Usage: just <recipe>
# Run `just --list` to see all available recipes.

set dotenv-load
set shell := ["bash", "-euo", "pipefail", "-c"]

# Run
[default]
[group('dev')]
run:
    echo "run"

# Clean artifacts
[group('dev')]
clean:
    echo "clean"

# Fix + Gate, prefer this recipe to save time instead of doing gate -> fix -> gate.
[group('qual')]
qual: fix ci

# Full check + test gate
[group('qual')]
ci: check test

# Check: format, lint, and flake outputs
[group('qual')]
check:
    nix flake check --all-systems --show-trace

# Run tests
[group('qual')]
test *args:
    echo "test"

# Fix: format and lint
[group('qual')]
fix:
    nix fmt

# Update flake inputs
[group('nix')]
flake-update:
    nix flake update

# Show flake outputs
[group('nix')]
flake-show:
    nix flake show --all-systems
