;;; my-theme.el --- My cutom emacs theme -*- lexical-binding: t; -*-

;;; Commentary:
;;; Code:

(deftheme my "My custom theme.")

(let* (
       (my-theme-title-base `(:inherit variable-pitch-text :foreground ,my-theme-col-s :weight bold))
       (my-theme-poster `(,@my-theme-title-base :height ,my-theme-font-size-h))
       (my-theme-title `(,@my-theme-title-base :height ,my-theme-font-size-x))
       (my-theme-heading `(,@my-theme-title-base :height ,my-theme-font-size-l))
       (my-theme-subheading `(,@my-theme-title-base :height ,my-theme-font-size-m))
       (my-theme-prominent `(:inherit variable-pitch-text :weight bold)))
  (custom-theme-set-faces
   'my

   `(default ((t (:family ,my-theme-fonts-mono :height ,my-theme-font-size-m :background ,my-theme-col-b :foreground ,my-theme-col-f))))
   `(fixed-pitch ((t (:family ,my-theme-fonts-mono :height ,my-theme-font-size-m))))
   `(variable-pitch ((t (:family ,my-theme-fonts-serif :height ,my-theme-font-size-m))))
   `(variable-pitch-text ((t (:family ,my-theme-fonts-sans :height ,my-theme-font-size-m))))

   `(ansi-color-black ((t (:foreground ,my-theme-col-b))))
   `(ansi-color-red ((t (:foreground ,my-theme-col-s))))
   `(ansi-color-green ((t (:foreground ,my-theme-col-p))))
   `(ansi-color-yellow ((t (:foreground ,my-theme-col-p))))
   `(ansi-color-blue ((t (:foreground ,my-theme-col-s))))
   `(ansi-color-magenta ((t (:foreground ,my-theme-col-s))))
   `(ansi-color-cyan ((t (:foreground ,my-theme-col-p))))
   `(ansi-color-white ((t (:foreground ,my-theme-col-m))))
   `(ansi-color-bright-black ((t (:foreground ,my-theme-col-o))))
   `(ansi-color-bright-red ((t (:foreground ,my-theme-col-s))))
   `(ansi-color-bright-green ((t (:foreground ,my-theme-col-p))))
   `(ansi-color-bright-yellow ((t (:foreground ,my-theme-col-p))))
   `(ansi-color-bright-blue ((t (:foreground ,my-theme-col-s))))
   `(ansi-color-bright-magenta ((t (:foreground ,my-theme-col-s))))
   `(ansi-color-bright-cyan ((t (:foreground ,my-theme-col-p))))
   `(ansi-color-bright-white ((t (:foreground ,my-theme-col-f))))

   `(cursor ((t (:background ,my-theme-col-f))))
   `(region ((t (:background ,my-theme-col-o))))
   `(highlight ((t (:background ,my-theme-col-o))))
   `(fringe ((t (:background ,my-theme-col-b))))
   `(link ((t (:inherit fixed-pitch :foreground ,my-theme-col-p :underline t))))
   `(link-visited ((t (:foreground ,my-theme-col-m :underline t))))
   `(line-number ((t (:background ,my-theme-col-b :foreground ,my-theme-col-m :weight bold))))
   `(line-number-current-line ((t (:background ,my-theme-col-b :foreground ,my-theme-col-f :weight bold))))
   `(vertical-border ((t (:background ,my-theme-col-b :foreground ,my-theme-col-o))))

   `(error ((t (:foreground ,my-theme-col-s :underline (:color ,my-theme-col-s :style wave)))))
   `(warning ((t (:foreground ,my-theme-col-p :underline (:color ,my-theme-col-p :style wave)))))

   `(mode-line ((t (:background ,my-theme-col-o :foreground ,my-theme-col-f))))
   `(mode-line-inactive ((t (:background ,my-theme-col-o :foreground ,my-theme-col-m))))
   `(header-line ((t (:inherit mode-line))))

   `(tab-line ((t (:inherit mode-line))))
   `(tab-line-tab ((t (:inherit mode-line))))
   `(tab-line-tab-current ((t (:inherit mode-line :background ,my-theme-col-b :foreground ,my-theme-col-m :weight bold))))
   `(tab-line-tab-inactive ((t (:inherit mode-line :foreground ,my-theme-col-m))))
   `(tab-line-tab-modified ((t (:foreground ,my-theme-col-p :weight bold))))

   `(tab-bar ((t (:inherit mode-line))))
   `(tab-bar-tab ((t (:inherit tab-bar))))
   `(tab-bar-tab-highlight ((t (:inherit tab-bar))))
   `(tab-bar-tab-inactive ((t (:inherit tab-bar :foreground ,my-theme-col-m))))

   `(speedbar-button-face ((t (:foreground ,my-theme-col-m))))
   `(speedbar-directory-face ((t (:foreground ,my-theme-col-s))))
   `(speedbar-file-face ((t (:foreground ,my-theme-col-f))))
   `(speedbar-selected-face ((t (:foreground ,my-theme-col-p :weight bold))))
   `(speedbar-separator-face ((t (:foreground ,my-theme-col-s :weight bold))))

   `(completions-common-part ((t (:foreground ,my-theme-col-m))))
   `(completions-first-difference ((t (:foreground ,my-theme-col-p :weight bold))))

   `(font-lock-constant-face ((t (:foreground ,my-theme-col-p))))
   `(font-lock-comment-face ((t (:inherit variable-pitch :foreground ,my-theme-col-m))))
   `(font-lock-keyword-face ((t (:foreground ,my-theme-col-m :weight bold))))
   `(font-lock-builtin-face ((t (:foreground ,my-theme-col-m))))
   `(font-lock-function-name-face ((t (:foreground ,my-theme-col-s))))
   `(font-lock-variable-name-face ((t (:foreground ,my-theme-col-f))))
   `(font-lock-type-face ((t (:foreground ,my-theme-col-f))))
   `(font-lock-string-face ((t (:foreground ,my-theme-col-p))))

   `(isearch ((t (:background ,my-theme-col-o :weight bold :underline (:color ,my-theme-col-s :style dashes)))))
   `(isearch-fail ((t (:foreground ,my-theme-col-s :weight bold))))
   `(lazy-highlight ((t (:background ,my-theme-col-o :weight bold :underline (:color ,my-theme-col-p :style dashes)))))

   `(log-view-message ((t (:foreground ,my-theme-col-m))))
   `(change-log-list ((t (:foreground ,my-theme-col-s))))

   `(log-edit-header ((t (:inherit variable-pitch-text :foreground ,my-theme-col-m))))
   `(log-edit-headers-separator ((t (:background ,my-theme-col-o :foreground ,my-theme-col-o :height 18))))
   `(log-edit-summary ((t (:inherit variable-pitch-text :foreground ,my-theme-col-f))))

   `(vc-dir-header ((t (:foreground ,my-theme-col-m))))
   `(vc-dir-file ((t (:inherit fixed-pitch))))
   `(vc-dir-directory ((t (:inherit dired-directory :foreground ,my-theme-col-m))))
   `(vc-dir-mark-indicator ((t (:foreground ,my-theme-col-p :weight bold))))
   `(vc-dir-status-edited ((t (:foreground ,my-theme-col-s))))

   `(dired-header ((t (:foreground ,my-theme-col-m :weight bold))))
   `(dired-directory ((t (:foreground ,my-theme-col-s :weight bold))))

   `(flymake-error ((t (:underline (:color ,my-theme-col-s :style wave)))))
   `(flymake-error-echo ((t (:foreground ,my-theme-col-s))))
   `(flymake-error-fringe ((t (:foreground ,my-theme-col-s))))
   `(flymake-warning ((t (:underline (:color ,my-theme-col-p :style wave)))))
   `(flymake-warning-echo ((t (:foreground ,my-theme-col-p))))
   `(flymake-warning-fringe ((t (:foreground ,my-theme-col-p))))
   `(flymake-note ((t (:underline (:color ,my-theme-col-m :style wave)))))
   `(flymake-note-echo ((t (:foreground ,my-theme-col-m))))
   `(flymake-note-fringe ((t (:foreground ,my-theme-col-m))))

   `(show-paren-match ((t (:background ,my-theme-col-o :foreground ,my-theme-col-p :weight bold))))
   `(show-paren-mismatch ((t (:background ,my-theme-col-s :foreground ,my-theme-col-f :weight bold))))

   `(message-header-subject ((t (:inherit variable-pitch-text :foreground ,my-theme-col-s))))
   `(message-header-content ((t (:inherit variable-pitch-text :foreground ,my-theme-col-f :slant italic))))
   `(message-header-other ((t (:inherit variable-pitch-text :foreground ,my-theme-col-f :slant italic))))
   `(message-header-from ((t (:inherit fixed-pitch :foreground ,my-theme-col-p))))
   `(message-header-to ((t (:inherit fixed-pitch :foreground ,my-theme-col-p))))
   `(message-header-name ((t (:inherit fixed-pitch :foreground ,my-theme-col-m))))
   `(message-header-cc ((t (:inherit fixed-pitch :foreground ,my-theme-col-m))))
   `(message-separator ((t (:inherit fixed-pitch :foreground ,my-theme-col-m))))

   `(gnus-server-offline ((t (:inherit fixed-pitch :foreground ,my-theme-col-s :weight bold))))
   `(gnus-header-subject ((t (:inherit variable-pitch-text :foreground ,my-theme-col-s))))
   `(gnus-header-content ((t (:inherit variable-pitch-text :foreground ,my-theme-col-f :slant italic))))
   `(gnus-header-from ((t (:inherit fixed-pitch :foreground ,my-theme-col-p))))
   `(gnus-header-name ((t (:inherit fixed-pitch :foreground ,my-theme-col-m))))
   `(gnus-summary-normal-read ((t (:inherit variable-pitch-text :foreground ,my-theme-col-m))))
   `(gnus-summary-normal-ancient ((t (:inherit gnus-summary-normal-read))))
   `(gnus-summary-normal-unread ((t (:inherit variable-pitch-text))))
   `(gnus-summary-normal-ticked ((t (:inherit gnus-summary-normal-unread :foreground ,my-theme-col-s))))
   `(gnus-group-mail-3-empty ((t (:foreground ,my-theme-col-p))))
   `(shr-text ((t (:inherit variable-pitch))))
   `(shr-code ((t (:inherit fixed-pitch :foreground ,my-theme-col-p))))
   `(shr-h1 ((t ,my-theme-title)))
   `(shr-h2 ((t ,my-theme-heading)))
   `(shr-h3 ((t ,my-theme-subheading)))
   `(shr-h4 ((t (:inherit shr-h3))))
   `(shr-h5 ((t (:inherit shr-h4))))
   `(shr-h6 ((t (:inherit shr-h5))))

   `(info-title-1 ((t ,my-theme-title)))
   `(info-title-2 ((t ,my-theme-heading)))
   `(info-title-3 ((t ,my-theme-subheading)))
   `(info-title-4 ((t (:inherit info-title-3))))
   `(info-menu-header ((t ,my-theme-prominent)))
   `(Info-quoted ((t (:inherit fixed-pitch :foreground ,my-theme-col-p))))

   `(markdown-ts-heading-1 ((t ,my-theme-title)))
   `(markdown-ts-heading-2 ((t ,my-theme-heading)))
   `(markdown-ts-heading-3 ((t ,my-theme-subheading)))
   `(markdown-ts-heading-4 ((t (:inherit markdown-ts-heading-3))))
   `(markdown-ts-heading-5 ((t (:inherit markdown-ts-heading-4))))
   `(markdown-ts-heading-6 ((t (:inherit markdown-ts-heading-5))))
   `(markdown-ts-code-span ((t (:inherit fixed-pitch :foreground ,my-theme-col-p))))
   `(markdown-ts-code-block ((t (:inherit fixed-pitch))))
   `(markdown-ts-code-block-markup-hidden ((t (:inherit fixed-pitch :background ,my-theme-col-o))))
   `(markdown-ts-table-delimiter-cell ((t (:inherit markdown-ts-table :foreground ,my-theme-col-m))))
   `(markdown-ts-delimiter ((t (:foreground ,my-theme-col-m))))
   `(markdown-ts-task-checked ((t (:inherit fixed-pitch :foreground ,my-theme-col-p :weight bold))))
   `(markdown-ts-task-unchecked ((t (:inherit fixed-pitch :foreground ,my-theme-col-s :weight bold))))
   `(markdown-ts-list-marker ((t (:inherit fixed-pitch :foreground ,my-theme-col-m :weight bold))))
   `(markdown-ts-bold ((t ,my-theme-prominent)))))

(provide-theme 'my)
;;; my-theme.el ends here
